### ISSUE TITLE
NXDN96 ISSUE

### ISSUE THREAD

**Issue by iz4tow** [LouisErigHerve/dsd#23]
Hi
I think there is an issue with NXDN96. I tried to decode many tracks without success, the output is confused. I don't think the tracks are encrypted because I can listen voices, but they are distorted (too fast maybe?)

**Comment by iz4tow** [comment]
You can find more users that are complaining about that here https://forums.radioreference.com/threads/dsd-1-8-3-dsd-1-8-4-do-not-decode-the-voice-of-nxdn48-and-nxdn96.437017/#post-3633654

**Comment by Dianlp471** [comment]
I would suggest you move to using dsd-fme it handles NXDN96 much better and for a bonus has a shitload more features.

**Comment by iz4tow** [comment]
I tried to use also dsd-fme but same results.

**Comment by LouisErigHerve** [comment]
Closing issue as reply can be found here : https://github.com/lwvmobile/dsd-fme/issues/70
