### ISSUE TITLE
dmr .....!!!!!

### ISSUE THREAD

**Issue by romanremus** [LouisErigHerve/dsd#24]
eric do you think you could help me with dmr rc4 ???? unfortunately in my country most of the dmr signals are encrypted with rc4 .... there are only a few that clearly have very rare activity ...... try better with cygwin from 0 .....

**Comment by LouisErigHerve** [comment]
Hello Romanremus,

Currently I’m offering training / courses on PMR encryption (and also electronics + software development services).

To be able to benefit from these trainings, several rules must be respected:
- You must be a professional (in radiocommunications, cybersecurity, security, electronics, computer science, cryptography…), represent a university or a government agency
- Classes are held on-site only (not online)
- First contact only over LinkedIn (you must have a LinkedIn account)
- All subjects can be adapted to your needs
- Courses are of course chargeable
- Payment must be made only by bank account transfer in Euro (no bitcoin or exotic money, only official moneys)

If you are interested feel free to contact me by LinkedIn indicating your company, its registration number and its VAT number, we will then discuss your project to find out how I can help you.

Louis

**Comment by romanremus** [comment]
I understood.....but unfortunately the money doesn't allow me to take a course.....I also have a sick child with whom I spend a lot of money for his health, and I can't afford other courses...even though I am authorized radio amateur and I would have liked enormously to listen to those dmr repeaters as well ...... Thanks Eric
    Pe duminică, 8 ianuarie 2023, 13:07:15 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


Hello Romanremus,

Currently I’m offering training / courses on PMR encryption (and also electronics + software development services).

To be able to benefit from these trainings, several rules must be respected:
   
   - You must be a professional (in radiocommunications, cybersecurity, security, electronics, computer science, cryptography…), represent a university or a government agency
   - Classes are held on-site only (not online)
   - First contact only over LinkedIn (you must have a LinkedIn account)
   - All subjects can be adapted to your needs
   - Courses are of course chargeable
   - Payment must be made only by bank account transfer in Euro (no bitcoin or exotic money, only official moneys)

If you are interested feel free to contact me by LinkedIn indicating your company, its registration number and its VAT number, we will then discuss your project to find out how I can help you.

Louis

**Comment by LouisErigHerve** [comment]
Here in France, I have a very greedy huge child who takes about 60% of everything I earn from me: the French State (champion number 1 all categories in taxation).

The services I offer are my livelihood, without these I have no salary at the end of the month…

If you can't pay you can try asking your boss to fund your training.

If your boss refuses, I couldn't do anything for you...

Alternatively, you can also try learning by yourself whatever you want. A tool like DSD-FME will make your job easier because it already decodes the IVs of each superframe, it supports late entry IV decoding and it’s free!

lwvmobile seems to have succeeded in decoding RC4 (no confirmation, I suppose it, based on the C code he made), so if he and I can do it you should be able to do it too.

Regards,

Louis

**Comment by romanremus** [comment]
Hello Eric .... I saw your new update to dsd .... to understand that now I can also enjoy those encrypted signals for me ????
    Pe marți, 10 ianuarie 2023, 10:59:10 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


Closed #24 as completed.

**Comment by LouisErigHerve** [comment]
I'm working on an online training about DMR encryption, DSD will be the main tool used to understand how the cryptography works, so to help my futures costumers I just added 2 generic commands that can be used to decode all DMR basic encrypt of all manufacturers.

**Comment by romanremus** [comment]
I tried eric for some dmr signals, even if I know the key to add it, I honestly couldn't do it ...... could you just send me what I could modify to work for me and I swear not to tell anyone and not to give dsd to no one.
    Pe sâmbătă, 14 ianuarie 2023, 18:55:04 EET, ***@***.*** ***@***.***> a scris:  
 
  
Hello Eric .... I saw your new update to dsd .... to understand that now I can also enjoy those encrypted signals for me ????
    Pe marți, 10 ianuarie 2023, 10:59:10 EET, Louis-Erig HERVE ***@***.***> a scris:  
 
 


Closed #24 as completed.
